var ELM = {
    //首页
    P_HOME: 'p_home',
    // 候选人
    P_CANDIDATELIST: 'p_candidateList',
    // 候选人详细页
    P_CANDIDATEDETAIL: 'p_candidateDetail',
    // 猎头列表
    P_HEADHUNTERLIST: 'p_headhunterList',
    // 猎头详细
    P_HEADHUNTERDETAIL: 'p_headhunterDetail',
    // 职位列表
    P_POSITIONLIST: 'p_positionList',
    // 发布职位
    P_POSITIONPOST: 'p_positionPost',
    // 职位详细
    P_POSITIONDETAIL: 'p_positionDetail',
    // 设置
    P_SETTING: 'p_setting',
    // 顶部导航
    M_HOME_TOPNAV: 'm_home_topNav',
    // 左侧导航
    M_HOME_LEFTNAV: 'm_home_leftNav',
    // 首页仪表盘
    M_HOME_DASHBOARD: 'm_home_dashboard',
    // 候选人
    M_HOME_CANDIDATE: 'm_home_candidate',
    // 职位
    M_HOME_POSITION: 'm_home_position',
    // 个人信息
    M_HOME_PROFILE: 'm_home_profile',
    // 顶部导航
    M_CANDIDATELIST_TOPNAV: 'm_candidateList_topNav',
    // 左侧导航
    M_CANDIDATELIST_LEFTNAV: 'm_candidateList_leftNav',
    // 仪表盘
    M_CANDIDATELIST_DASHBOARD: 'm_candidateList_dashboard',
    // 搜索
    M_CANDIDATELIST_SEARCH: 'm_candidateList_search',
    // 候选人列表
    M_CANDIDATELIST: 'm_candidateList',
    // 顶部导航
    M_CANDIDATEDETAIL_TOPNAV: 'm_candidateDetail_topNav',
    // 左侧导航
    M_CANDIDATEDETAIL_LEFTNAV: 'm_candidateDetail_leftNav',
    // 顶部操作
    M_CANDIDATEDETAIL_OPATIONTOP: 'm_candidateDetail_opationTop',
    // 底部操作
    M_CANDIDATEDETAIL_OPATIONDOWN: 'm_candidateDetail_opationDown',
    // 顶部导航
    M_HEADHUNTERLIST_TOPNAV: 'm_headhunterList_topNav',
    // 左侧导航
    M_HEADHUNTERLIST_LEFTNAV: 'm_headhunterList_leftNav',
    // 仪表盘
    M_HEADHUNTERLIST_DASHBOARD: 'm_headhunterList_dashboard',
    // 猎头列表
    M_HEADHUNTERLIST_LIST: 'm_headhunterList_list',
    // 右侧滑窗
    M_HEADHUNTERDETAIL_TAP: 'm_headhunterDetail_tap',
    // 顶部导航
    M_POSITIONLIST_TOPNAV: 'm_positionList_topNav',
    // 左侧导航
    M_POSITIONLIST_LEFTNAV: 'm_positionList_leftNav',
    // 仪表盘
    M_POSITIONLIST_DASHBOARD: 'm_positionList_dashboard',
    // 职位列表
    M_POSITIONLIST_LIST: 'm_positionList_list',
    // 职位搜索
    M_POSITIONLIST_SEARCH: 'm_positionList_search',
    // 右侧滑窗
    M_POSITIONLIST_TAP: 'm_positionList_tap',
    // 顶部导航
    M_SETTING_TOPNAV: 'm_setting_topNav',
    // 左侧导航
    M_SETTING_LEFTNAV: 'm_setting_leftNav',
    // 消息
    P_MESSAGE: 'p_message',
    // 交流消息
    P_MESSAGE_COMMUNICATION: 'p_message_communication',
    // 系统消息
    P_MESSAGE_SYSTEM: 'p_message_system',
    // 发件箱
    P_MESSAGE_SEND: 'p_message_send',
    // 公司
    E_HOME_TOPNAV_LOGO: 'e_home_topNav_logo',
    // 消息
    E_HOME_TOPNAV_MESSAGE: 'e_home_topNav_message',
    // 个人信息
    E_HOME_TOPNAV_INFO: 'e_home_topNav_info',
    // 首页
    E_HOME_LEFTNAV_HOME: 'e_home_leftNav_home',
    // 候选人
    E_HOME_LEFTNAV_CANDIDATE: 'e_home_leftNav_candidate',
    // 猎头
    E_HOME_LEFTNAV_HEADHUNTER: 'e_home_leftNav_headhunter',
    // 职位
    E_HOME_LEFTNAV_POSITION: 'e_home_leftNav_position',
    // 合作猎头
    E_HOME_DASHBOARD_COOPERATIONHEADHUNTER: 'e_home_dashboard_cooperationHeadhunter',
    // 职位
    E_HOME_DASHBOARD_ALLPOSITION: 'e_home_dashboard_allPosition',
    // 新推荐候选人
    E_HOME_DASHBOARD_NEWCANDIDATE: 'e_home_dashboard_newCandidate',
    // 面试确认
    E_HOME_DASHBOARD_INTERVIEWCANDIDATE: 'e_home_dashboard_interviewCandidate',
    // 待定
    E_HOME_DASHBOARD_PENDINGCANDIDATE: 'e_home_dashboard_pendingCandidate',
    // 评估中
    E_HOME_DASHBOARD_ASSESSCANDIDATE: 'e_home_dashboard_assessCandidate',
    // 团队
    E_HOME_DASHBOARD_TEAM: 'e_home_dashboard_team',
    // 个人
    E_HOME_DASHBOARD_MEMBER: 'e_home_dashboard_member',
    // 面试
    M_HOME_INTERVIEW: 'm_home_interview',
    // 面试名称
    E_HOME_INTERVIEW_NAME: 'e_home_interview_name',
    // 职位名称
    E_HOME_POSITION_NAME: 'e_home_position_name',
    // 职位刷新
    E_HOME_POSITION_UPDATEDATE: 'e_home_position_updateDate',
    // 发布职位
    E_HOME_POSITION_POST: 'e_home_position_post',
    // 职位消息
    M_HOME_POSITIONMESSAGE: 'm_home_positionMessage',
    // 全部消息
    E_HOME_POSITIONMESSAGE_ALL: 'e_home_positionMessage_all',
    // 消息名
    E_HOME_POSITIONMESSAGE_NAME: 'e_home_positionMessage_name',
    // 合同
    E_HOME_CONTRACT: 'e_home_contract',
    // 职位
    E_HOME_POSITION: 'e_home_position',
    // 评价
    E_HOME_EVALUATE: 'e_home_evaluate',
    // 财务
    E_HOME_FINANCE: 'e_home_finance',
    // 组织
    E_HOME_GROUP: 'e_home_group',
    // 右滑窗
    M_HOME_TAB: 'm_home_tab',
    // 职位详情
    E_HOME_TAB_INFO: 'e_home_tab_Info',
    // 职位调研
    E_HOME_TAB_RESEARCH: 'e_home_tab_research',
    // 职位备注，动态
    E_HOME_TAB_COMMENT: 'e_home_tab_comment',
    // 关闭
    E_HOME_TAB_CLOSE: 'e_home_tab_close',
    // 公司
    E_CANDIDATELIST_TOPNAV_LOGO: 'e_candidateList_topNav_logo',
    // 消息
    E_CANDIDATELIST_TOPNAV_MESSAGE: 'e_candidateList_topNav_message',
    // 个人信息
    E_CANDIDATELIST_TOPNAV_INFO: 'e_candidateList_topNav_info',
    // 首页
    E_CANDIDATELIST_LEFTNAV_HOME: 'e_candidateList_leftNav_home',
    // 候选人
    E_CANDIDATELIST_LEFTNAV_CANDIDATE: 'e_candidateList_leftNav_candidate',
    // 猎头
    E_CANDIDATELIST_LEFTNAV_HEADHUNTER: 'e_candidateList_leftNav_headhunter',
    // 职位
    E_CANDIDATELIST_LEFTNAV_POSITION: 'e_candidateList_leftNav_position',
    // 全部
    E_CANDIDATELIST_DASHBOARD_ALL: 'e_candidateList_dashboard_all',
    // 待定
    E_CANDIDATELIST_DASHBOARD_PENDING: 'e_candidateList_dashboard_pending',
    // 新推荐
    E_CANDIDATELIST_DASHBOARD_RECOMMEND: 'e_candidateList_dashboard_recommend',
    // 评估中
    E_CANDIDATELIST_DASHBOARD_ASSESS: 'e_candidateList_dashboard_assess',
    // 面试申请
    E_CANDIDATELIST_DASHBOARD_IVAPPLICATION: 'e_candidateList_dashboard_ivApplication',
    // 面试中
    E_CANDIDATELIST_DASHBOARD_INTERVIEW: 'e_candidateList_dashboard_interview',
    // 取消面试
    E_CANDIDATELIST_DASHBOARD_IVCANCEL: 'e_candidateList_dashboard_ivCancel',
    // 已 offer
    E_CANDIDATELIST_DASHBOARD_OFFER: 'e_candidateList_dashboard_offer',
    // 已入职
    E_CANDIDATELIST_DASHBOARD_ONBOARD: 'e_candidateList_dashboard_onBoard',
    // 已过保
    E_CANDIDATELIST_DASHBOARD_PERIOD: 'e_candidateList_dashboard_period',
    // 已拒绝
    E_CANDIDATELIST_DASHBOARD_REJECT: 'e_candidateList_dashboard_reject',
    // 已撤销
    E_CANDIDATELIST_DASHBOARD_REVOCATION: 'e_candidateList_dashboard_revocation',
    // 搜索
    E_CANDIDATELIST_SEARCH: 'e_candidateList_search',
    // 列表模块
    M_CANDIDATELIST_LIST: 'm_candidateList_list',
    // 姓名
    E_CANDIDATELIST_LIST_NAME: 'e_candidateList_list_name',
    // 职位
    E_CANDIDATELIST_LIST_POSITION: 'e_candidateList_list_position',
    // 猎头
    E_CANDIDATELIST_LIST_HEADHUNTER: 'e_candidateList_list_headhunter',
    // 发布消息
    E_CANDIDATELIST_LIST_SENDMESSAGE: 'e_candidateList_list_sendMessage',
    // 进程-新
    E_CANDIDATELIST_LIST_PROCESSXIN: 'e_candidateList_list_processXin',
    // 进程-评
    E_CANDIDATELIST_LIST_PROCESSPIN: 'e_candidateList_list_processPin',
    // 进程-面
    E_CANDIDATELIST_LIST_PROCESSMIAN: 'e_candidateList_list_processMian',
    // 进程-O
    E_CANDIDATELIST_LIST_PROCESSOFFER: 'e_candidateList_list_processOffer',
    // 进程-到
    E_CANDIDATELIST_LIST_PROCESSDAO: 'e_candidateList_list_processDao',
    // 进程-付
    E_CANDIDATELIST_LIST_PROCESSFU: 'e_candidateList_list_processFu',
    // 进程-过
    E_CANDIDATELIST_LIST_PROCESSGUO: 'e_candidateList_list_processGuo',
    // 进程-拒
    E_CANDIDATELIST_LIST_PROCESSJU: 'e_candidateList_list_processJu',
    // 进程-待
    E_CANDIDATELIST_LIST_PROCESSDAI: 'e_candidateList_list_processDai',
    // 操作-优先级
    E_CANDIDATELIST_LIST_OPERATEPRIORITY: 'e_candidateList_list_operatePriority',
    // 操作-恢复面试
    E_CANDIDATELIST_LIST_OPERATEREINTERVIEW: 'e_candidateList_list_operateReInterview',
    // 操作-待定候选人
    E_CANDIDATELIST_LIST_OPERATEPENDING: 'e_candidateList_list_operatePending',
    // 操作-OFFER
    E_CANDIDATELIST_LIST_OPERATEOFFER: 'e_candidateList_list_operateOffer',
    // 操作-拒绝候选人
    E_CANDIDATELIST_LIST_OPERATEREJECT: 'e_candidateList_list_operateReject',
    // 操作-转移候选人
    E_CANDIDATELIST_LIST_OPERATEMOVE: 'e_candidateList_list_operateMove',
    // 操作-转发简历
    E_CANDIDATELIST_LIST_OPERATESENDCV: 'e_candidateList_list_operateSendCV',
    // 操作-发信
    E_CANDIDATELIST_LIST_OPERATEMESSAGE: 'e_candidateList_list_operateMessage',
    // 右滑窗
    M_CANDIDATELIST_TAB: 'm_candidateList_tab',
    // 猎头
    E_CANDIDATELIST_TAB_HEADHUNTERINFO: 'e_candidateList_tab_headhunterInfo',
    // 合作职位
    E_CANDIDATELIST_TAB_COOPERATIONJOBS: 'e_candidateList_tab_cooperationJobs',
    // 成功职位
    E_CANDIDATELIST_TAB_SUCCESSJOBS: 'e_candidateList_tab_successJobs',
    // 关闭
    E_CANDIDATELIST_TAB_CLOSE: 'e_candidateList_tab_close',
    // 保存图片
    E_CANDIDATELIST_TAB_SAVEIMG: 'e_candidateList_tab_saveImg',
    // 还原
    E_CANDIDATELIST_TAB_REVERT: 'e_candidateList_tab_revert',
    // 公司
    E_CANDIDATEDETAIL_TOPNAV_LOGO: 'e_candidateDetail_topNav_logo',
    // 消息
    E_CANDIDATEDETAIL_TOPNAV_MESSAGE: 'e_candidateDetail_topNav_message',
    // 个人信息
    E_CANDIDATEDETAIL_TOPNAV_INFO: 'e_candidateDetail_topNav_info',
    // 首页
    E_CANDIDATEDETAIL_LEFTNAV_HOME: 'e_candidateDetail_leftNav_home',
    // 候选人
    E_CANDIDATEDETAIL_LEFTNAV_CANDIDATE: 'e_candidateDetail_leftNav_candidate',
    // 猎头
    E_CANDIDATEDETAIL_LEFTNAV_HEADHUNTER: 'e_candidateDetail_leftNav_headhunter',
    // 职位
    E_CANDIDATEDETAIL_LEFTNAV_POSITION: 'e_candidateDetail_leftNav_position',
    // 候选人详细顶模块
    M_CANDIDATEDETAIL_TOP: 'm_candidateDetail_top',
    // 优先级
    E_CANDIDATEDETAIL_TOP_PRIORITY: 'e_candidateDetail_top_priority',
    // 恢复面试
    E_CANDIDATEDETAIL_TOP_INTERVIEW: 'e_candidateDetail_top_interview',
    // 待定候选人
    E_CANDIDATEDETAIL_TOP_PENDING: 'e_candidateDetail_top_pending',
    // Offer
    E_CANDIDATEDETAIL_TOP_OFFER: 'e_candidateDetail_top_offer',
    // 拒绝候选人
    E_CANDIDATEDETAIL_TOP_REJECT: 'e_candidateDetail_top_reject',
    // 转移候选人
    E_CANDIDATEDETAIL_TOP_MOVE: 'e_candidateDetail_top_move',
    // 转发简历
    E_CANDIDATEDETAIL_TOP_SEND: 'e_candidateDetail_top_send',
    // 发信
    E_CANDIDATEDETAIL_TOP_SENDMESSAGE: 'e_candidateDetail_top_sendMessage',
    // 下载报告
    E_CANDIDATEDETAIL_TOP_DOWNREPORT: 'e_candidateDetail_top_downReport',
    // 打印
    E_CANDIDATEDETAIL_TOP_PRINT: 'e_candidateDetail_top_print',
    // 公司
    E_HEADHUNTERLIST_TOPNAV_LOGO: 'e_headhunterList_topNav_logo',
    // 消息
    E_HEADHUNTERLIST_TOPNAV_MESSAGE: 'e_headhunterList_topNav_message',
    // 个人信息
    E_HEADHUNTERLIST_TOPNAV_INFO: 'e_headhunterList_topNav_info',
    // 首页
    E_HEADHUNTERLIST_LEFTNAV_HOME: 'e_headhunterList_leftNav_home',
    // 候选人
    E_HEADHUNTERLIST_LEFTNAV_CANDIDATE: 'e_headhunterList_leftNav_candidate',
    // 猎头
    E_HEADHUNTERLIST_LEFTNAV_HEADHUNTER: 'e_headhunterList_leftNav_headhunter',
    // 职位
    E_HEADHUNTERLIST_LEFTNAV_POSITION: 'e_headhunterList_leftNav_position',
    // 常用猎头
    E_HEADHUNTERLIST_DASHBOARD_COMMON: 'e_headhunterList_dashboard_common',
    //合作猎头
    E_HEADHUNTERLIST_DASHBOARD_COOPERATION: 'e_headhunterList_dashboard_cooperation',
    // 申请合作
    E_HEADHUNTERLIST_DASHBOARD_APPLY: 'e_headhunterList_dashboard_apply',
    // 平台猎头
    E_HEADHUNTERLIST_DASHBOARD_ALL: 'e_headhunterList_dashboard_all',
    // 姓名
    E_HEADHUNTERLIST_LIST_NAME: 'e_headhunterList_list_name',
    // 移除常用猎头
    E_HEADHUNTERLIST_LIST_MOVE: 'e_headhunterList_list_move',
    // 设置为常用猎头
    E_HEADHUNTERLIST_LIST_SETTING: 'e_headhunterList_list_setting',
    // 翻页
    E_HEADHUNTERLIST_LIST_PAGE: 'e_headhunterList_list_page',
    // 右滑窗
    M_HEADHUNTERLIST_TAB: 'm_headhunterList_tab',
    // 猎头详细
    E_HEADHUNTERLIST_TAB_HEADHUNTERINFO: 'e_headhunterList_tab_headhunterInfo',
    // 合作职位
    E_HEADHUNTERLIST_TAB_COOPERATIONJOBS: 'e_headhunterList_tab_cooperationJobs',
    // 成功职位
    E_HEADHUNTERLIST_TAB_SUCCESSJOBS: 'e_headhunterList_tab_successJobs',
    // 关闭按钮
    E_HEADHUNTERLIST_TAB_CLOSE: 'e_headhunterList_tab_close',
    // 保存图片
    E_HEADHUNTERLIST_TAB_SAVEIMG: 'e_headhunterList_tab_saveImg',
    // 还原
    E_HEADHUNTERLIST_TAB_REVERT: 'e_headhunterList_tab_revert',
    // 公司
    E_POSITIONLIST_TOPNAV_LOGO: 'e_positionList_topNav_logo',
    // 消息
    E_POSITIONLIST_TOPNAV_MESSAGE: 'e_positionList_topNav_message',
    // 个人信息
    E_POSITIONLIST_TOPNAV_INFO: 'e_positionList_topNav_info',
    // 首页
    E_POSITIONLIST_LEFTNAV_HOME: 'e_positionList_leftNav_home',
    // 候选人
    E_POSITIONLIST_LEFTNAV_CANDIDATE: 'e_positionList_leftNav_candidate',
    // 猎头
    E_POSITIONLIST_LEFTNAV_HEADHUNTER: 'e_positionList_leftNav_headhunter',
    // 职位
    E_POSITIONLIST_LEFTNAV_POSITION: 'e_positionList_leftNav_position',
    // 全部
    E_POSITIONLIST_DASHBOARD_ALL: 'e_positionList_dashboard_all',
    // 开放职位
    E_POSITIONLIST_DASHBOARD_OPEN: 'e_positionList_dashboard_open',
    // 无职调
    E_POSITIONLIST_DASHBOARD_NORESEARCH: 'e_positionList_dashboard_noResearch',
    // 无候选人
    E_POSITIONLIST_DASHBOARD_NOCANDIDATE: 'e_positionList_dashboard_noCandidate',
    // 暂停
    E_POSITIONLIST_DASHBOARD_PENDING: 'e_positionList_dashboard_pending',
    //删除草稿
    E_POSITIONLIST_LIST_DRAFT_DELETE: 'e_positionlist_list_draft_delete',
    // 申请关闭
    E_POSITIONLIST_DASHBOARD_APPLYCLOSE: 'e_positionList_dashboard_applyClose',
    // 关闭
    E_POSITIONLIST_DASHBOARD_CLOSE: 'e_positionList_dashboard_close',
    // 草稿
    E_POSITIONLIST_DASHBOARD_DRAFT: 'e_positionList_dashboard_draft',
    // 发布职位
    E_POSITIONLIST_DASHBOARD_POST: 'e_positionList_dashboard_post',
    // 名称
    E_POSITIONLIST_LIST_NAME: 'e_positionList_list_name',
    // 候选人-全部
    E_POSITIONLIST_LIST_CANDIDATEALL: 'e_positionList_list_candidateAll',
    // 候选人-新推荐
    E_POSITIONLIST_LIST_CANDIDATENEW: 'e_positionList_list_candidateNew',
    // 候选人-评估
    E_POSITIONLIST_LIST_CANDIDATEASSESS: 'e_positionList_list_candidateAssess',
    // 候选人-面试
    E_POSITIONLIST_LIST_CANDIDATEINTERIEW: 'e_positionList_list_candidateInteriew',
    // 候选人-撤销
    E_POSITIONLIST_LIST_CANDIDATEREVOCATION: 'e_positionList_list_candidateRevocation',
    // 翻页
    E_POSITIONLIST_LIST_CANDIDATEPAGE: 'e_positionList_list_candidatePage',
    // 操作-优先级
    E_POSITIONLIST_LIST_OPERATEPRIORITY: 'e_positionList_list_operatePriority',
    // 候选人-编辑
    E_POSITIONLIST_LIST_OPERATEEDIT: 'e_positionList_list_operateEdit',
    // 候选人-暂停职位
    E_POSITIONLIST_LIST_OPERATEPENDING: 'e_positionList_list_operatePending',
    // 候选人-复制
    E_POSITIONLIST_LIST_OPERATECOPY: 'e_positionList_list_operateCopy',
    // 候选人-关闭
    E_POSITIONLIST_LIST_OPERATECLOSE: 'e_positionList_list_operateClose',
    // 候选人-变更候选人
    E_POSITIONLIST_LIST_OPERATECHANGEOWNER: 'e_positionList_list_operateChangeOwner',
    // 候选人-修改期望到岗时间
    E_POSITIONLIST_LIST_OPERATEONBOARDDATE: 'e_positionList_list_operateOnBoardDate',
    // 候选人-添加说明
    E_POSITIONLIST_LIST_OPERATECOMMENT: 'e_positionList_list_operateComment',
    // 搜索模块
    M_POSITIONSEARCH: 'm_positionSearch',
    // 搜索
    E_POSITIONSEARCH_SEARCH: 'e_positionSearch_search',
    // 右滑窗
    M_POSITIONLIST_TAB: 'm_positionList_tab',
    // 职位详情
    E_POSITIONLIST_TAB_INFO: 'e_positionList_tab_info',
    // 职位调研
    E_POSITIONLIST_TAB_RESEARCH: 'e_positionList_tab_research',
    // 备注，动态
    E_POSITIONLIST_TAB_COMMENT: 'e_positionList_tab_comment',
    // 关闭
    E_POSITIONLIST_TAB_CLOSE: 'e_positionList_tab_close',
    // 公司
    E_SETTING_TOPNAV_LOGO: 'e_setting_topNav_logo',
    // 消息
    E_SETTING_TOPNAV_MESSAGE: 'e_setting_topNav_message',
    // 个人信息
    E_SETTING_TOPNAV_INFO: 'e_setting_topNav_info',
    // 首页
    E_SETTING_LEFTNAV_HOME: 'e_setting_leftNav_home',
    // 候选人
    E_SETTING_LEFTNAV_CANDIDATE: 'e_setting_leftNav_candidate',
    // 猎头
    E_SETTING_LEFTNAV_HEADHUNTER: 'e_setting_leftNav_headhunter',
    // 职位
    E_SETTING_LEFTNAV_POSITION: 'e_setting_leftNav_position',
    // 交流消息模块
    M_MESSAGE_COMMUNICATION: 'm_message_communication',
    // 标记已读
    E_MESSAGE_COMMUNICATION_READ: 'e_message_communication_read',
    // 删除消息
    E_MESSAGE_COMMUNICATION_DELETE: 'e_message_communication_delete',
    // 主题
    E_MESSAGE_COMMUNICATION_NAME: 'e_message_communication_name',
    // 回复
    E_MESSAGE_COMMUNICATION_REPLY: 'e_message_communication_reply',
    // 翻页
    E_MESSAGE_COMMUNICATION_PAGE: 'e_message_communication_page',
    // 系统消息
    M_MESSAGE_SYSTEM: 'm_message_system',
    // 标记已读
    E_MESSAGE_SYSTEM_READ: 'e_message_system_read',
    // 删除消息
    E_MESSAGE_SYSTEM_DELETE: 'e_message_system_delete',
    // 名称
    E_MESSAGE_SYSTEM_NAME: 'e_message_system_name',
    // 翻页
    E_MESSAGE_SYSTEM_PAGE: 'e_message_system_page',
    // 发送箱
    M_MESSAGE_SEND: 'm_message_send',
    // 删除消息
    E_MESSAGE_SEND_DELETE: 'e_message_send_delete',
    // 主题
    E_MESSAGE_SEND_NAME: 'e_message_send_name',
    // 翻页
    E_MESSAGE_SEND_PAGE: 'e_message_send_page',
    // 组织架构
    P_ORGANIZATION: 'p_organization',
    // 用户
    M_ORGANIZATION_USER: 'm_organization_user',
    // 添加用户
    E_GROUP_USER_ADD: 'e_group_user_add',
    // 编辑用户
    E_GROUP_USER_EDIT: 'e_group_user_edit',
    // 删除用户
    E_GROUP_USER_DELETE: 'e_group_user_delete',
    // 组
    M_ORGANIZATION_GROUP: 'm_organization_group',
    // 删除组
    E_ORGANIZATION_GROUP_DELETE: 'e_organization_group_delete',
    // 添加组
    E_ORGANIZATION_GROUP_ADD: 'e_organization_group_add',
    // 组权限
    E_ORGANIZATION_GROUP_PURVIEW: 'e_organization_group_purview',
    // 添加用户
    E_ORGANIZATION_GROUP_ADDUSER: 'e_organization_group_addUser',
    // 删除用户
    E_ORGANIZATION_GROUP_DELETEUSER: 'e_organization_group_deleteUser',

    //邀请用户频道
    P_INVITE: 'p_invite',
    //发送邀请邮件
    E_INVITE_EMAIL_SEND: 'e_invite_email_send',
    //邀请邮箱输入框激活
    E_INVITE_EMAILINPUT_ACTIVE: 'e_invite_emailinput_active',
    //激活邀请链接输入框
    E_INVITE_LINKINPUT_ACTIVE: 'e_invite_linkinput_active',
    //复制邀请链接
    E_INVITE_COPY: 'e_invite_copy'
};
